front:
  domain: https://ladie.gtio.work

spring:
  datasource:
    hikari:
      catalog: ladies_health
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
