server:
  port: 16807
  address: 127.0.0.1
  forward-headers-strategy: framework

# 回滚时限
rollback:
  expire: 300

springdoc:
  packages-to-scan: com.system.ladiesHealth.controller

spring:
  profiles:
    active:
      - dev
      - private

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 0
      maximum-pool-size: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: true
        useUnbufferedInput: false
        useReadAheadInput: false
        useSSL: false
        useLegacyDatetimeCode: false
        serverTimezone: Asia/Shanghai
        allowPublicKeyRetrieval: true
        useUnicode: true
        characterEncoding: utf-8
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          mime-types: application/json,application/xml,text/xml
          min-request-size: 2048
        response:
          enabled: true
      client:
        config:
          default:
            loggerLevel: basic
      okhttp:
        enabled: true
      httpclient:
        enabled: false
        disable-ssl-validation: false

jwt:
  token-header: Authorization
  token-prefix: Bearer
  alg: HS256
  refresh-expire: 86400

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

    com:
      system:
        ladiesHealth:
          component:
            client: debug


async:
  thread:
    core_pool_size: 4
    max_pool_size: 16
    queue_capacity: 2048
    name:
      prefix: LadiesHealth-
    keep_alive_seconds: 120
    rejection-policy: java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy



okhttp:
  read-timeout: 240
  write-timeout: 120
  proxy:
    host: 127.0.0.1
    port: 16503
