front:
  domain: http://localhost:[*],http://127.0.0.1:[*],https://ladie.gtio.work

spring:
  datasource:
    hikari:
      catalog: ladies_health_dev
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
