front:
  domain: '*'

spring:
  datasource:
    hikari:
      catalog: ladies_health_dev
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
