front:
  domain: '*'

spring:
  datasource:
    url: jdbc:mysql://175.178.43.44:3306/ladies_health_dev
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
