server:
  port: 16807

# 回滚时限
rollback:
  expire: 300

springdoc:
  packages-to-scan: com.system.ladiesHealth.controller

spring:
  profiles:
    active:
      - dev
      - private

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 0
      maximum-pool-size: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: true
        useUnbufferedInput: false
        useReadAheadInput: false
        useSSL: false
        useLegacyDatetimeCode: false
        serverTimezone: Asia/Shanghai
        allowPublicKeyRetrieval: true
        useUnicode: true
        characterEncoding: utf-8
  jpa:
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

jwt:
  token-header: Authorization
  token-prefix: Bearer
  alg: HS256
  refresh-expire: 86400
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
              BasicExtractor: trace

async:
  thread:
    core_pool_size: 4
    max_pool_size: 16
    queue_capacity: 2048
    name:
      prefix: LadiesHealth-
    keep_alive_seconds: 120
    rejection-policy: java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy

